reachc: error: REACH_ERR_EVAL79

 ./Err_RecursionDepthLimit.rsh:4:23:application

 4|   const k = (x) => f(x(x));

    Recursion depth limit exceeded, more than 65536 calls; who would need more than that many?

Trace:
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  in "x" from (./Err_RecursionDepthLimit.rsh:4:17:function exp) at (./Err_RecursionDepthLimit.rsh:4:23:application)
  ...

For further explanation of this error, see: docs.reach.sh/ref-error-codes.html/#%28tech._REACH_ERR_EVAL79%29

